import { useLocale } from "../i18n/locale";
import { getTranslations } from "../i18n/translations";
export function ServicesOverview() {
  const t = getTranslations(useLocale()); const [feature, photoSupport, ...compactBenefits] = t.whyChooseUs;
  return <section className="section-band" id="services"><div className="section-shell">
    <div className="mb-7 max-w-3xl"><p className="text-sm font-bold text-teal">{t.benefits.eyebrow}</p><h2 className="mt-2 text-2xl font-bold leading-tight tracking-[-0.02em] text-pine sm:text-3xl">{t.benefits.title}</h2><p className="mt-3 text-sm leading-6 text-ink/68 sm:text-base">{t.benefits.intro}</p></div>
    <div className="benefits-mosaic grid gap-4 lg:grid-cols-[1.12fr_0.88fr]">
      <article className="benefits-mosaic-feature group relative min-h-[390px] overflow-hidden rounded-[18px] bg-pine shadow-card sm:min-h-[470px]"><img src={feature.image} alt={feature.imageAlt} loading="lazy" width={900} height={760} className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-pine via-pine/35 to-transparent" aria-hidden="true" /><div className="absolute inset-x-0 bottom-0 p-5 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-gold">{t.benefits.featureLabel}</p><h3 className="mt-3 max-w-md text-2xl font-bold leading-tight tracking-[-0.02em] sm:text-3xl">{feature.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-white/86 sm:text-base sm:leading-7">{feature.text}</p></div></article>
      <div className="grid gap-4 sm:grid-cols-2"><article className="benefits-mosaic-support overflow-hidden rounded-[16px] border border-ink/10 bg-white shadow-card sm:col-span-2 sm:grid sm:grid-cols-[0.9fr_1.1fr]"><figure className="h-[190px] overflow-hidden bg-pine sm:h-auto sm:min-h-[220px]"><img src={photoSupport.image} alt={photoSupport.imageAlt} loading="lazy" width={640} height={520} className="h-full w-full object-cover" /></figure><div className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-teal">{t.benefits.supportLabel}</p><h3 className="mt-3 text-xl font-bold leading-snug text-pine">{photoSupport.title}</h3><p className="mt-3 text-sm leading-6 text-ink/76">{photoSupport.text}</p></div></article>
      {compactBenefits.map((item, index) => <article className={`benefits-mosaic-support overflow-hidden rounded-[16px] border border-ink/10 shadow-card ${index === 0 ? "bg-mint" : "bg-white"}`} key={item.title}><figure className="h-[136px] overflow-hidden bg-pine"><img src={item.image} alt={item.imageAlt} loading="lazy" width={520} height={280} className="h-full w-full object-cover" /></figure><div className="p-5"><p className="text-xs font-semibold text-gold">0{index + 3}</p><h3 className="mt-2 text-lg font-bold leading-snug text-pine">{item.title}</h3><p className="mt-3 text-sm leading-6 text-ink/74">{item.text}</p></div></article>)}</div>
    </div>
  </div></section>;
}
